name: Run Tests 🧪

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Build Tools
        run: sudo apt-get install -y build-essential

      - name: Build Code
        run: make

      - name: Run Tests
        run: |
          if make test; then
            echo "Tests Passed! ✅"
          else
            echo "Tests Failed! ❌"
            exit 1
          fi

